/**
 * This file is part of the securitypro package.
 *
 * @author Mathias Reker
 * @copyright Mathias Reker
 * @license Commercial Software License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

"use strict";!function(t){let e=function(e){this.element=t(e)};e.prototype={constructor:e,show:function(){let e,a,n,i=this.element,s=i.closest("ul:not(.dropdown-menu)"),o=i.attr("data-target");o||(o=(o=i.attr("href"))&&o.replace(/.*(?=#[^\s]*$)/,"")),i.parent("li").hasClass("active")||(e=s.find(".active:last a")[0],n=t.Event("show",{relatedTarget:e}),i.trigger(n),n.isDefaultPrevented()||(a=t(o),this.activate(i.parent("li"),s),this.activate(a,a.parent(),function(){i.trigger({type:"shown",relatedTarget:e})})))},activate:function(e,a,n){let i=a.find("> .active"),s=n&&t.support.transition&&i.hasClass("fade");function o(){i.removeClass("active").find("> .dropdown-menu > .active").removeClass("active"),e.addClass("active"),s?(e[0].offsetWidth,e.addClass("in")):e.removeClass("fade"),e.parent(".dropdown-menu")&&e.closest("li.dropdown").addClass("active"),n&&n()}s?i.one(t.support.transition.end,o):o(),i.removeClass("in"),scroll(0,0)}};let a=t.fn.tab;t.fn.tab=function(a){return this.each(function(){let n=t(this),i=n.data("tab");i||n.data("tab",i=new e(this)),"string"==typeof a&&i[a]()})},t.fn.tab.Constructor=e,t.fn.tab.noConflict=function(){return t.fn.tab=a,this},t(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(e){e.preventDefault(),t(this).tab("show")})}(window.jQuery),function(t){t.createTabs=function(){let e;t("#content").find('form [id^="fieldset"]').length&&(e='<div class="col-lg-2"><div id="module-tabs" class="list-group">',t.each(t("#content").find('form [id^="fieldset"]'),function(){let a;a=t(this).find(".panel-heading, legend"),e+='<a href="#'+t(this).attr("id")+'" class="list-group-item" id="'+t(this).attr("id")+'_performancelite" data-toggle="tab">'+a.html()+"</a>",t(this).addClass("tab-pane")}),e+="</div></div>",t("#content").find("form").wrap("<div class='row'></div>").before(e).addClass("col-lg-10 tab-content"),t("#content").find("form > br").remove(),t("#content").find("#module-tabs a:first").tab("show").addClass("active"),t("#content").find(".list-group-item").on("click",function(){let e=t(this).parent().closest(".list-group").children(".active");e.hasClass("active")&&e.removeClass("active"),t(this).addClass("active")}))}}(jQuery),$(document).ready(function(){$.createTabs(),$('a[data-toggle="tab"]').on("shown",function(t){localStorage.setItem("lastTab",$(t.target).attr("id"))});let t=localStorage.getItem("lastTab"),e=$("#"+t);t&&(e.tab("show"),$("#fieldset_0_performancelite").removeClass("active"),e.addClass("active"))}),$(document).ready(function(){$("#module-tabs").after("<div id='module-tabs' class='list-group'><a class='list-group-item' style='text-align: center;'><i class='icon-info'></i> "+performancelite.versionName+" "+performancelite.moduleVersion+" | <i class='icon-info'></i> "+performancelite.cmsName+" "+performancelite.cmsVersion+"</a></div>")});
